// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: proto/monitor.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MonitorService_AddMonitor_FullMethodName        = "/monitor.MonitorService/AddMonitor"
	MonitorService_RemoveMonitor_FullMethodName     = "/monitor.MonitorService/RemoveMonitor"
	MonitorService_GetMonitor_FullMethodName        = "/monitor.MonitorService/GetMonitor"
	MonitorService_ListMonitors_FullMethodName      = "/monitor.MonitorService/ListMonitors"
	MonitorService_GetMonitorStatus_FullMethodName  = "/monitor.MonitorService/GetMonitorStatus"
	MonitorService_ListMonitorStatus_FullMethodName = "/monitor.MonitorService/ListMonitorStatus"
)

// MonitorServiceClient is the client API for MonitorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MonitorServiceClient interface {
	AddMonitor(ctx context.Context, in *Target, opts ...grpc.CallOption) (*MonitorResponse, error)
	RemoveMonitor(ctx context.Context, in *MonitorID, opts ...grpc.CallOption) (*MonitorResponse, error)
	GetMonitor(ctx context.Context, in *MonitorID, opts ...grpc.CallOption) (*Target, error)
	ListMonitors(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TargetList, error)
	GetMonitorStatus(ctx context.Context, in *MonitorID, opts ...grpc.CallOption) (*MonitorStatus, error)
	ListMonitorStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MonitorStatusList, error)
}

type monitorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMonitorServiceClient(cc grpc.ClientConnInterface) MonitorServiceClient {
	return &monitorServiceClient{cc}
}

func (c *monitorServiceClient) AddMonitor(ctx context.Context, in *Target, opts ...grpc.CallOption) (*MonitorResponse, error) {
	out := new(MonitorResponse)
	err := c.cc.Invoke(ctx, MonitorService_AddMonitor_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) RemoveMonitor(ctx context.Context, in *MonitorID, opts ...grpc.CallOption) (*MonitorResponse, error) {
	out := new(MonitorResponse)
	err := c.cc.Invoke(ctx, MonitorService_RemoveMonitor_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) GetMonitor(ctx context.Context, in *MonitorID, opts ...grpc.CallOption) (*Target, error) {
	out := new(Target)
	err := c.cc.Invoke(ctx, MonitorService_GetMonitor_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) ListMonitors(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TargetList, error) {
	out := new(TargetList)
	err := c.cc.Invoke(ctx, MonitorService_ListMonitors_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) GetMonitorStatus(ctx context.Context, in *MonitorID, opts ...grpc.CallOption) (*MonitorStatus, error) {
	out := new(MonitorStatus)
	err := c.cc.Invoke(ctx, MonitorService_GetMonitorStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) ListMonitorStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MonitorStatusList, error) {
	out := new(MonitorStatusList)
	err := c.cc.Invoke(ctx, MonitorService_ListMonitorStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonitorServiceServer is the server API for MonitorService service.
// All implementations must embed UnimplementedMonitorServiceServer
// for forward compatibility
type MonitorServiceServer interface {
	AddMonitor(context.Context, *Target) (*MonitorResponse, error)
	RemoveMonitor(context.Context, *MonitorID) (*MonitorResponse, error)
	GetMonitor(context.Context, *MonitorID) (*Target, error)
	ListMonitors(context.Context, *Empty) (*TargetList, error)
	GetMonitorStatus(context.Context, *MonitorID) (*MonitorStatus, error)
	ListMonitorStatus(context.Context, *Empty) (*MonitorStatusList, error)
	mustEmbedUnimplementedMonitorServiceServer()
}

// UnimplementedMonitorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMonitorServiceServer struct {
}

func (UnimplementedMonitorServiceServer) AddMonitor(context.Context, *Target) (*MonitorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMonitor not implemented")
}
func (UnimplementedMonitorServiceServer) RemoveMonitor(context.Context, *MonitorID) (*MonitorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveMonitor not implemented")
}
func (UnimplementedMonitorServiceServer) GetMonitor(context.Context, *MonitorID) (*Target, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonitor not implemented")
}
func (UnimplementedMonitorServiceServer) ListMonitors(context.Context, *Empty) (*TargetList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMonitors not implemented")
}
func (UnimplementedMonitorServiceServer) GetMonitorStatus(context.Context, *MonitorID) (*MonitorStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonitorStatus not implemented")
}
func (UnimplementedMonitorServiceServer) ListMonitorStatus(context.Context, *Empty) (*MonitorStatusList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMonitorStatus not implemented")
}
func (UnimplementedMonitorServiceServer) mustEmbedUnimplementedMonitorServiceServer() {}

// UnsafeMonitorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonitorServiceServer will
// result in compilation errors.
type UnsafeMonitorServiceServer interface {
	mustEmbedUnimplementedMonitorServiceServer()
}

func RegisterMonitorServiceServer(s grpc.ServiceRegistrar, srv MonitorServiceServer) {
	s.RegisterService(&MonitorService_ServiceDesc, srv)
}

func _MonitorService_AddMonitor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Target)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).AddMonitor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_AddMonitor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).AddMonitor(ctx, req.(*Target))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_RemoveMonitor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonitorID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).RemoveMonitor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_RemoveMonitor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).RemoveMonitor(ctx, req.(*MonitorID))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_GetMonitor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonitorID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).GetMonitor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_GetMonitor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).GetMonitor(ctx, req.(*MonitorID))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_ListMonitors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).ListMonitors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_ListMonitors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).ListMonitors(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_GetMonitorStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonitorID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).GetMonitorStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_GetMonitorStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).GetMonitorStatus(ctx, req.(*MonitorID))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_ListMonitorStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).ListMonitorStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_ListMonitorStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).ListMonitorStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// MonitorService_ServiceDesc is the grpc.ServiceDesc for MonitorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MonitorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monitor.MonitorService",
	HandlerType: (*MonitorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddMonitor",
			Handler:    _MonitorService_AddMonitor_Handler,
		},
		{
			MethodName: "RemoveMonitor",
			Handler:    _MonitorService_RemoveMonitor_Handler,
		},
		{
			MethodName: "GetMonitor",
			Handler:    _MonitorService_GetMonitor_Handler,
		},
		{
			MethodName: "ListMonitors",
			Handler:    _MonitorService_ListMonitors_Handler,
		},
		{
			MethodName: "GetMonitorStatus",
			Handler:    _MonitorService_GetMonitorStatus_Handler,
		},
		{
			MethodName: "ListMonitorStatus",
			Handler:    _MonitorService_ListMonitorStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/monitor.proto",
}

const (
	IPGeoService_QueryIPGeo_FullMethodName = "/monitor.IPGeoService/QueryIPGeo"
)

// IPGeoServiceClient is the client API for IPGeoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IPGeoServiceClient interface {
	QueryIPGeo(ctx context.Context, in *IPRequest, opts ...grpc.CallOption) (*IPGeoResponse, error)
}

type iPGeoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIPGeoServiceClient(cc grpc.ClientConnInterface) IPGeoServiceClient {
	return &iPGeoServiceClient{cc}
}

func (c *iPGeoServiceClient) QueryIPGeo(ctx context.Context, in *IPRequest, opts ...grpc.CallOption) (*IPGeoResponse, error) {
	out := new(IPGeoResponse)
	err := c.cc.Invoke(ctx, IPGeoService_QueryIPGeo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IPGeoServiceServer is the server API for IPGeoService service.
// All implementations must embed UnimplementedIPGeoServiceServer
// for forward compatibility
type IPGeoServiceServer interface {
	QueryIPGeo(context.Context, *IPRequest) (*IPGeoResponse, error)
	mustEmbedUnimplementedIPGeoServiceServer()
}

// UnimplementedIPGeoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIPGeoServiceServer struct {
}

func (UnimplementedIPGeoServiceServer) QueryIPGeo(context.Context, *IPRequest) (*IPGeoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryIPGeo not implemented")
}
func (UnimplementedIPGeoServiceServer) mustEmbedUnimplementedIPGeoServiceServer() {}

// UnsafeIPGeoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IPGeoServiceServer will
// result in compilation errors.
type UnsafeIPGeoServiceServer interface {
	mustEmbedUnimplementedIPGeoServiceServer()
}

func RegisterIPGeoServiceServer(s grpc.ServiceRegistrar, srv IPGeoServiceServer) {
	s.RegisterService(&IPGeoService_ServiceDesc, srv)
}

func _IPGeoService_QueryIPGeo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPGeoServiceServer).QueryIPGeo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPGeoService_QueryIPGeo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPGeoServiceServer).QueryIPGeo(ctx, req.(*IPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IPGeoService_ServiceDesc is the grpc.ServiceDesc for IPGeoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IPGeoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monitor.IPGeoService",
	HandlerType: (*IPGeoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryIPGeo",
			Handler:    _IPGeoService_QueryIPGeo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/monitor.proto",
}
